// Generated by gencpp from file q3/bot_pose.msg
// DO NOT EDIT!


#ifndef Q3_MESSAGE_BOT_POSE_H
#define Q3_MESSAGE_BOT_POSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <geometry_msgs/Pose2D.h>
#include <std_msgs/String.h>

namespace q3
{
template <class ContainerAllocator>
struct bot_pose_
{
  typedef bot_pose_<ContainerAllocator> Type;

  bot_pose_()
    : location()
    , direction()  {
    }
  bot_pose_(const ContainerAllocator& _alloc)
    : location(_alloc)
    , direction(_alloc)  {
  (void)_alloc;
    }



   typedef  ::geometry_msgs::Pose2D_<ContainerAllocator>  _location_type;
  _location_type location;

   typedef  ::std_msgs::String_<ContainerAllocator>  _direction_type;
  _direction_type direction;





  typedef boost::shared_ptr< ::q3::bot_pose_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::q3::bot_pose_<ContainerAllocator> const> ConstPtr;

}; // struct bot_pose_

typedef ::q3::bot_pose_<std::allocator<void> > bot_pose;

typedef boost::shared_ptr< ::q3::bot_pose > bot_posePtr;
typedef boost::shared_ptr< ::q3::bot_pose const> bot_poseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::q3::bot_pose_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::q3::bot_pose_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::q3::bot_pose_<ContainerAllocator1> & lhs, const ::q3::bot_pose_<ContainerAllocator2> & rhs)
{
  return lhs.location == rhs.location &&
    lhs.direction == rhs.direction;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::q3::bot_pose_<ContainerAllocator1> & lhs, const ::q3::bot_pose_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace q3

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::q3::bot_pose_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::q3::bot_pose_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::q3::bot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::q3::bot_pose_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::q3::bot_pose_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::q3::bot_pose_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::q3::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "7b486e5b854c9adb55fb5f9c3c07f96f";
  }

  static const char* value(const ::q3::bot_pose_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x7b486e5b854c9adbULL;
  static const uint64_t static_value2 = 0x55fb5f9c3c07f96fULL;
};

template<class ContainerAllocator>
struct DataType< ::q3::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "q3/bot_pose";
  }

  static const char* value(const ::q3::bot_pose_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::q3::bot_pose_<ContainerAllocator> >
{
  static const char* value()
  {
    return "geometry_msgs/Pose2D location\n"
"std_msgs/String direction\n"
"\n"
"================================================================================\n"
"MSG: geometry_msgs/Pose2D\n"
"# Deprecated\n"
"# Please use the full 3D pose.\n"
"\n"
"# In general our recommendation is to use a full 3D representation of everything and for 2D specific applications make the appropriate projections into the plane for their calculations but optimally will preserve the 3D information during processing.\n"
"\n"
"# If we have parallel copies of 2D datatypes every UI and other pipeline will end up needing to have dual interfaces to plot everything. And you will end up with not being able to use 3D tools for 2D use cases even if they're completely valid, as you'd have to reimplement it with different inputs and outputs. It's not particularly hard to plot the 2D pose or compute the yaw error for the Pose message and there are already tools and libraries that can do this for you.\n"
"\n"
"\n"
"# This expresses a position and orientation on a 2D manifold.\n"
"\n"
"float64 x\n"
"float64 y\n"
"float64 theta\n"
"\n"
"================================================================================\n"
"MSG: std_msgs/String\n"
"string data\n"
;
  }

  static const char* value(const ::q3::bot_pose_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::q3::bot_pose_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.location);
      stream.next(m.direction);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct bot_pose_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::q3::bot_pose_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::q3::bot_pose_<ContainerAllocator>& v)
  {
    s << indent << "location: ";
    s << std::endl;
    Printer< ::geometry_msgs::Pose2D_<ContainerAllocator> >::stream(s, indent + "  ", v.location);
    s << indent << "direction: ";
    s << std::endl;
    Printer< ::std_msgs::String_<ContainerAllocator> >::stream(s, indent + "  ", v.direction);
  }
};

} // namespace message_operations
} // namespace ros

#endif // Q3_MESSAGE_BOT_POSE_H
